# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

Facebook_Key: "515050272593862"
Facebook_Secret: "5a055cd7e0240f32bbe52618084d8559"

#Google_Key: "1010521804242-hee9n648vodq15ighobl3v5js3efoqnl.apps.googleusercontent.com"
Google_Key: "1006282632868-8svqdeuar3om3hg3a0huqpld3t34bf2r.apps.googleusercontent.com"
#Google_Secret: "UPNeyHX42HIIJ9yTvoMczilV"
Google_Secret: "YXC2nF75OI4efowqOgtxTwpL"

#Kakao_Key: "039f5aa36770cb24e49fc0ac22596fdf"
Kakao_Key: "8cc26b8d5872fb0d410aa3d79d878c55"

# recaptcha hanryumoa2 (v2 체크박스) 
# https://www.google.com/recaptcha/admin/site/347234968/setup 
RECAPTCHA_SITE_KEY: 6LeYYrIUAAAAAD4rbtzBLfJsSKSBYGO_ErWjWgfR
RECAPTCHA_SECRET_KEY: 6LeYYrIUAAAAAPqdjXGb9Posk36urxThnlRCBvLz

# recaptcha hanryumoa2 (v3)
#RECAPTCHA_SITE_KEY: 6LdAYrIUAAAAAAbk5iE3EeQou_yYCEu0oN8sQYNw
#RECAPTCHA_SECRET_KEY: 6LdAYrIUAAAAAKwKShwN9OzX7DqomaSXsAFRc5Io

MAX_READ_WITHOUT_LOGIN: '0'

#ELASTICSEARCH_SERVER_IP: '10.3.0.9:81'
ELASTICSEARCH_SERVER_HOST: '127.0.0.1:9200'

DB_USERNAME: root 
DB_PASSWORD: todwkdduawkd

